/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Initialize.h"

//#include "GPIO.h"
//#include "Drive_Output.h"
//#include "Frequency_Sample.h"
//#include "Analog_Sample.h"
//#include "Communicate.h"
//#include "Schedule.h"

#include "zf_device_icm20602.h"
#include "zf_driver_uart.h"
#include "stdio.h"

#include "Bsp.h"

#include "App_Config.h"
#include "FreeRTOS.h"
#include "task.h"
#include "Intern_Task.h"

//#include "MCMCAN.h"
//#include "CANTASK.h"

#include "Qspi_L9658.h"

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    initial();

    xTaskCreate(X_TASK_5ms, "5ms_TASK", configMINIMAL_STACK_SIZE, NULL, 0, NULL);

    /* Create LED1 app task */
//    xTaskCreate(task_app_led1, "APP LED1", configMINIMAL_STACK_SIZE, NULL, 0, NULL);

    /* Create LED2 app task */
//    xTaskCreate(task_app_led2, "APP LED2", configMINIMAL_STACK_SIZE, NULL, 0, NULL);

    /* Start the scheduler */
//    vTaskStartScheduler();



    while(1)
    {
//        run_schedule();

//        measure_PWM();
//        readEVADC();

        //transmitCanMessage();

//        icm20602_get_acc();
//        icm20602_get_gyro();
//        printf("acc_x = %f , acc_y = %f , acc_z = %f , gyro_x = %f , gyro_y = %f , gyro_z = %f\r\n",
//                acc_x, acc_y, acc_z, gyro_x, gyro_y, gyro_z);
//        printf("duty_cycle_fl = %f\r\n", g_measuredPwmDutyCycle[0]);


//        printf("vout/vref = %f\r\n", g_result_adc[4]);
//        printf("111\r\n");

//        CAN0Data_Send(1);
//        CAN2Data_Send(2);

        transferData();
//        printf("FL_Acc = %d , FR_Acc = %d , RL_Acc = %d , RR_Acc = %d \r\n",
//                FL_Acc, FR_Acc, RL_Acc, RR_Acc);
        printf("FL_Acc = %f , FR_Acc = %f , RL_Acc = %f , RR_Acc = %f \r\n",
                        f32_FL_Acc, f32_FR_Acc, f32_RL_Acc, f32_RR_Acc);


    }
}

/* Required FreeRTOS callback, called in case of a stack overflow.
 * For the sake of simplicity, this function will loop indefinitely
 * and the root cause can be confirmed by using a debugger
 */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    while (1)
    {
        __nop();
    }
}


//-------------------------------------------------------------------------     // printf 重定向 此部分不允许用户更改
//-------------------------------------------------------------------------------------------------------------------
//  @brief      重定向printf 到串口
//  @param      ch      需要打印的字节
//  @param      stream  数据流
//  @note       此函数由编译器自带库里的printf所调用
//-------------------------------------------------------------------------------------------------------------------
int fputc(int ch, FILE *stream)
{
    uart_write_byte(UART_0, (char)ch);
    return(ch);
}
