/********************************************************************************************************************
 * \file MCMCAN.c
 * \copyright Copyright (C) Infineon Technologies AG 2020
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "MCMCAN.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
McmcanType                  g_mcmcan;                       /* Global MCMCAN configuration and control structure    */
McmcanType                  g_mcmcan1;                      /* Global MCMCAN1 configuration and control structure   */
McmcanType                  g_mcmcan2;                      /* Global MCMCAN2 configuration and control structure   */
IfxPort_Pin_Config          g_led1;                         /* Global LED1 configuration and control structure      */
IfxPort_Pin_Config          g_led2;                         /* Global LED2 configuration and control structure      */
IfxPort_Pin_Config          g_led3;                         /* Global LED3 configuration and control structure      */
IFX_CONST IfxCan_Can_Pins Can0PortInf0 = {
        .padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1,
        .rxPin = &IfxCan_RXD00B_P20_7_IN,
        .rxPinMode = IfxPort_InputMode_pullUp,
        .txPin = &IfxCan_TXD00_P20_8_OUT,
        .txPinMode = IfxPort_OutputMode_pushPull
};

IFX_CONST IfxCan_Can_Pins Can1PortInf0 = {
        .padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1,
        .rxPin = &IfxCan_RXD10A_P00_1_IN,
        .rxPinMode = IfxPort_InputMode_pullUp,
        .txPin = &IfxCan_TXD10_P13_0_OUT,
        .txPinMode = IfxPort_OutputMode_pushPull
};

IFX_CONST IfxCan_Can_Pins Can2PortInf0 = {
        .padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1,
        .rxPin = &IfxCan_RXD20A_P10_5_IN,
        .rxPinMode = IfxPort_InputMode_pullUp,
        .txPin = &IfxCan_TXD20_P10_6_OUT,
        .txPinMode = IfxPort_OutputMode_pushPull
};
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define Interrupt Service Routine.
 * This macro:
 * - defines linker section as .intvec_tc<vector number>_<interrupt priority>.
 * - defines compiler specific attribute for the interrupt functions.
 * - defines the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(canIsrTxHandler, 0, ISR_PRIORITY_CAN_TX);
IFX_INTERRUPT(canIsrRxHandler, 0, ISR_PRIORITY_CAN_FIFO0_RX);
IFX_INTERRUPT(canIsrTxHandler1, 0, ISR_PRIORITY_CAN1_TX);
IFX_INTERRUPT(canIsrRxHandler1, 0, ISR_PRIORITY_CAN1_FIFO0_RX);
IFX_INTERRUPT(canIsrTxHandler2, 3, ISR_PRIORITY_CAN2_TX);
IFX_INTERRUPT(canIsrRxHandler2, 3, ISR_PRIORITY_CAN2_FIFO0_RX);
//IFX_INTERRUPT(canIsrTxHandler1, 0, ISR_PRIORITY_CAN1_TX);
//IFX_INTERRUPT(canIsrRxHandler1, 0, ISR_PRIORITY_CAN1_RX);

/* Interrupt Service Routine (ISR) called once the TX interrupt has been generated.
 * Turns on the LED1 to indicate successful CAN message transmission.
 */
void canIsrTxHandler(void)
{
    /* Clear the "Transmission Completed" interrupt flag */
    //����
    IfxCan_Node_clearInterruptFlag(g_mcmcan.canSrcNode.node, IfxCan_Interrupt_transmissionCompleted);
    /* Just to indicate that the CAN message has been transmitted by turning on LED1 */
    IfxPort_setPinLow(g_led1.port, g_led1.pinIndex);

    //����
//    IfxCan_Node_clearInterruptFlag(g_mcmcan.canDstNode.node,IfxCan_Interrupt_messageStoredToDedicatedRxBuffer);
//    /* Read the received CAN message */
//    IfxCan_Can_readMessage(&g_mcmcan.canDstNode, &g_mcmcan.rxMsg, g_mcmcan.rxData);
    /* Check if the received data matches with the transmitted one */
//    if( ( g_mcmcan.rxData[0] == g_mcmcan.txData[0] ) &&
//        ( g_mcmcan.rxData[1] == g_mcmcan.txData[1] ) &&
//        ( g_mcmcan.rxMsg.messageId == g_mcmcan.txMsg.messageId ) )
//    {
//        /* Turn on the LED2 to indicate correctness of the received message */
//        IfxPort_setPinLow(g_led2.port, g_led2.pinIndex);
//    }

}

void canIsrTxHandler1(void)
{
    /* Clear the "Transmission Completed" interrupt flag */
    //����
    IfxCan_Node_clearInterruptFlag(g_mcmcan1.canSrcNode.node, IfxCan_Interrupt_transmissionCompleted);
    /* Just to indicate that the CAN message has been transmitted by turning on LED1 */
    IfxPort_setPinLow(g_led3.port, g_led3.pinIndex);

    //����
//    IfxCan_Node_clearInterruptFlag(g_mcmcan.canDstNode.node,IfxCan_Interrupt_messageStoredToDedicatedRxBuffer);
//    /* Read the received CAN message */
//    IfxCan_Can_readMessage(&g_mcmcan.canDstNode, &g_mcmcan.rxMsg, g_mcmcan.rxData);
    /* Check if the received data matches with the transmitted one */
//    if( ( g_mcmcan.rxData[0] == g_mcmcan.txData[0] ) &&
//        ( g_mcmcan.rxData[1] == g_mcmcan.txData[1] ) &&
//        ( g_mcmcan.rxMsg.messageId == g_mcmcan.txMsg.messageId ) )
//    {
//        /* Turn on the LED2 to indicate correctness of the received message */
//        IfxPort_setPinLow(g_led2.port, g_led2.pinIndex);
//    }

}

void canIsrTxHandler2(void)
{
    /* Clear the "Transmission Completed" interrupt flag */
    //����
    IfxCan_Node_clearInterruptFlag(g_mcmcan2.canSrcNode.node, IfxCan_Interrupt_transmissionCompleted);
    /* Just to indicate that the CAN message has been transmitted by turning on LED1 */
    IfxPort_setPinLow(g_led3.port, g_led3.pinIndex);

    //����
//    IfxCan_Node_clearInterruptFlag(g_mcmcan.canDstNode.node,IfxCan_Interrupt_messageStoredToDedicatedRxBuffer);
//    /* Read the received CAN message */
//    IfxCan_Can_readMessage(&g_mcmcan.canDstNode, &g_mcmcan.rxMsg, g_mcmcan.rxData);
    /* Check if the received data matches with the transmitted one */
//    if( ( g_mcmcan.rxData[0] == g_mcmcan.txData[0] ) &&
//        ( g_mcmcan.rxData[1] == g_mcmcan.txData[1] ) &&
//        ( g_mcmcan.rxMsg.messageId == g_mcmcan.txMsg.messageId ) )
//    {
//        /* Turn on the LED2 to indicate correctness of the received message */
//        IfxPort_setPinLow(g_led2.port, g_led2.pinIndex);
//    }

}

/* Interrupt Service Routine (ISR) called once the RX interrupt has been generated.
 * Compares the content of the received CAN message with the content of the transmitted CAN message
 * and in case of success, turns on the LED2 to indicate successful CAN message reception.
 */
void canIsrRxHandler(void)
{
    /* Clear the "Message stored to Dedicated RX Buffer" interrupt flag */
    IfxCan_Node_clearInterruptFlag(g_mcmcan.canDstNode.node, IfxCan_Interrupt_rxFifo0NewMessage);

    /* Read the received CAN message */
    g_mcmcan.rxMsg.readFromRxFifo0 = TRUE;
    //g_mcmcan.rxMsg.readFromRxFifo1 = FALSE;

    IfxCan_Can_readMessage(&g_mcmcan.canDstNode, &g_mcmcan.rxMsg, g_mcmcan.rxData);
    IfxPort_setPinState(g_led2.port, g_led2.pinIndex,  IfxPort_State_toggled);

    /* Check if the received data matches with the transmitted one */
//    if( ( g_mcmcan.rxData[0] == g_mcmcan.txData[0] ) &&
//        ( g_mcmcan.rxData[1] == g_mcmcan.txData[1] ) &&
//        ( g_mcmcan.rxMsg.messageId == g_mcmcan.txMsg.messageId ) )
//    {
//        /* Turn on the LED2 to indicate correctness of the received message */
//        IfxPort_setPinLow(g_led2.port, g_led2.pinIndex);
//    }
}

void canIsrRxHandler1(void)
{
    /* Clear the "Message stored to Dedicated RX Buffer" interrupt flag */
    IfxCan_Node_clearInterruptFlag(g_mcmcan1.canDstNode.node, IfxCan_Interrupt_rxFifo0NewMessage);

    /* Read the received CAN message */
    g_mcmcan1.rxMsg.readFromRxFifo0 = TRUE;
    //g_mcmcan1.rxMsg.readFromRxFifo1 = FALSE;

    IfxCan_Can_readMessage(&g_mcmcan1.canDstNode, &g_mcmcan1.rxMsg, g_mcmcan1.rxData);
    IfxPort_setPinState(g_led2.port, g_led2.pinIndex,  IfxPort_State_toggled);

    /* Check if the received data matches with the transmitted one */
//    if( ( g_mcmcan.rxData[0] == g_mcmcan.txData[0] ) &&
//        ( g_mcmcan.rxData[1] == g_mcmcan.txData[1] ) &&
//        ( g_mcmcan.rxMsg.messageId == g_mcmcan.txMsg.messageId ) )
//    {
//        /* Turn on the LED2 to indicate correctness of the received message */
//        IfxPort_setPinLow(g_led2.port, g_led2.pinIndex);
//    }
}


void canIsrRxHandler2(void)
{
    /* Clear the "Message stored to Dedicated RX Buffer" interrupt flag */
    IfxCan_Node_clearInterruptFlag(g_mcmcan2.canDstNode.node, IfxCan_Interrupt_rxFifo0NewMessage);

    /* Read the received CAN message */
    g_mcmcan2.rxMsg.readFromRxFifo0 = TRUE;
    //g_mcmcan1.rxMsg.readFromRxFifo1 = FALSE;

    IfxCan_Can_readMessage(&g_mcmcan2.canDstNode, &g_mcmcan2.rxMsg, g_mcmcan2.rxData);
    IfxPort_setPinState(g_led2.port, g_led2.pinIndex,  IfxPort_State_toggled);

    /* Check if the received data matches with the transmitted one */
//    if( ( g_mcmcan.rxData[0] == g_mcmcan.txData[0] ) &&
//        ( g_mcmcan.rxData[1] == g_mcmcan.txData[1] ) &&
//        ( g_mcmcan.rxMsg.messageId == g_mcmcan.txMsg.messageId ) )
//    {
//        /* Turn on the LED2 to indicate correctness of the received message */
//        IfxPort_setPinLow(g_led2.port, g_led2.pinIndex);
//    }
}



/* Function to initialize MCMCAN module and nodes related for this application use case */
void initMcmcan(void)
{
    IfxCan_Can_initModuleConfig(&g_mcmcan.canConfig, &MODULE_CAN0);

    IfxCan_Can_initModule(&g_mcmcan.canModule, &g_mcmcan.canConfig);


    IfxCan_Can_initNodeConfig(&g_mcmcan.canNodeConfig, &g_mcmcan.canModule);


    g_mcmcan.canNodeConfig.nodeId = IfxCan_NodeId_0;


    g_mcmcan.canNodeConfig.frame.type = IfxCan_FrameType_transmitAndReceive;


    g_mcmcan.canNodeConfig.baudRate.baudrate = 500000;
    g_mcmcan.canNodeConfig.baudRate.prescaler = 0;
    g_mcmcan.canNodeConfig.baudRate.samplePoint = 8000;
    g_mcmcan.canNodeConfig.baudRate.syncJumpWidth = 2000;
    g_mcmcan.canNodeConfig.baudRate.timeSegment1 = 3;
    g_mcmcan.canNodeConfig.baudRate.timeSegment2 = 10;

    g_mcmcan.canNodeConfig.pins = &Can0PortInf0;


    g_mcmcan.canNodeConfig.interruptConfig.transmissionCompletedEnabled = TRUE;

    g_mcmcan.canNodeConfig.interruptConfig.rxFifo0NewMessageEnabled = TRUE;


    g_mcmcan.canNodeConfig.interruptConfig.traco.priority = ISR_PRIORITY_CAN_TX;
    g_mcmcan.canNodeConfig.interruptConfig.traco.interruptLine = IfxCan_InterruptLine_0;
    g_mcmcan.canNodeConfig.interruptConfig.traco.typeOfService = IfxSrc_Tos_cpu0;



    g_mcmcan.canNodeConfig.interruptConfig.rxf0n.priority = ISR_PRIORITY_CAN_FIFO0_RX;
    g_mcmcan.canNodeConfig.interruptConfig.rxf0n.interruptLine = IfxCan_InterruptLine_1;
    g_mcmcan.canNodeConfig.interruptConfig.rxf0n.typeOfService = IfxSrc_Tos_cpu0;

    g_mcmcan.canNodeConfig.rxConfig.rxMode = IfxCan_RxMode_fifo0;
    g_mcmcan.canNodeConfig.rxConfig.rxFifo0DataFieldSize = IfxCan_DataFieldSize_8;
    g_mcmcan.canNodeConfig.rxConfig.rxFifo0Size = 15;

    g_mcmcan.canNodeConfig.filterConfig.messageIdLength = IfxCan_MessageIdLength_both;
    g_mcmcan.canNodeConfig.filterConfig.standardListSize = 1;
    g_mcmcan.canNodeConfig.filterConfig.extendedListSize = 0;
    g_mcmcan.canNodeConfig.filterConfig.standardFilterForNonMatchingFrames = IfxCan_NonMatchingFrame_reject;
    g_mcmcan.canNodeConfig.filterConfig.extendedFilterForNonMatchingFrames = IfxCan_NonMatchingFrame_reject;
    g_mcmcan.canNodeConfig.filterConfig.rejectRemoteFramesWithStandardId = TRUE;
    g_mcmcan.canNodeConfig.filterConfig.rejectRemoteFramesWithExtendedId = TRUE;

    IfxCan_Can_initNode(&g_mcmcan.canSrcNode, &g_mcmcan.canNodeConfig);

    IfxCan_Can_initNode(&g_mcmcan.canDstNode, &g_mcmcan.canNodeConfig);

    IfxCan_Filter filter;

    filter.number = 0;
    filter.type = IfxCan_FilterType_range;
    filter.elementConfiguration = IfxCan_FilterElementConfiguration_storeInRxFifo0;
    filter.id1 = 0;
    filter.id2 = 10;
    //filter.rxBufferOffset = IfxCan_RxBufferId_0;
    IfxCan_Can_setStandardFilter(&g_mcmcan.canDstNode, &filter);


    IfxCan_Can_initMessage(&g_mcmcan.rxMsg);
    g_mcmcan.rxMsg.readFromRxFifo0=TRUE;
    memset((void *)(&g_mcmcan.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_DATA_PAYLOAD * sizeof(uint32));
    IfxCan_Can_initMessage(&g_mcmcan.txMsg);
}

void initMcmcan1(void)
{
    IfxCan_Can_initModuleConfig(&g_mcmcan1.canConfig, &MODULE_CAN1);

    IfxCan_Can_initModule(&g_mcmcan1.canModule, &g_mcmcan1.canConfig);


    IfxCan_Can_initNodeConfig(&g_mcmcan1.canNodeConfig, &g_mcmcan1.canModule);


    g_mcmcan1.canNodeConfig.nodeId = IfxCan_NodeId_0;


    g_mcmcan1.canNodeConfig.frame.type = IfxCan_FrameType_transmitAndReceive;


    g_mcmcan1.canNodeConfig.baudRate.baudrate = 500000;
    g_mcmcan1.canNodeConfig.baudRate.prescaler = 0;
    g_mcmcan1.canNodeConfig.baudRate.samplePoint = 8000;
    g_mcmcan1.canNodeConfig.baudRate.syncJumpWidth = 2000;
    g_mcmcan1.canNodeConfig.baudRate.timeSegment1 = 3;
    g_mcmcan1.canNodeConfig.baudRate.timeSegment2 = 10;

    g_mcmcan1.canNodeConfig.pins = &Can1PortInf0;


    g_mcmcan1.canNodeConfig.interruptConfig.transmissionCompletedEnabled = TRUE;

    g_mcmcan1.canNodeConfig.interruptConfig.rxFifo0NewMessageEnabled = TRUE;


    g_mcmcan1.canNodeConfig.interruptConfig.traco.priority = ISR_PRIORITY_CAN1_TX;
    g_mcmcan1.canNodeConfig.interruptConfig.traco.interruptLine = IfxCan_InterruptLine_2;
    g_mcmcan1.canNodeConfig.interruptConfig.traco.typeOfService = IfxSrc_Tos_cpu0;



    g_mcmcan1.canNodeConfig.interruptConfig.rxf0n.priority = ISR_PRIORITY_CAN1_FIFO0_RX;
    g_mcmcan1.canNodeConfig.interruptConfig.rxf0n.interruptLine = IfxCan_InterruptLine_3;
    g_mcmcan1.canNodeConfig.interruptConfig.rxf0n.typeOfService = IfxSrc_Tos_cpu0;

    g_mcmcan1.canNodeConfig.rxConfig.rxMode = IfxCan_RxMode_fifo0;
    g_mcmcan1.canNodeConfig.rxConfig.rxFifo0DataFieldSize = IfxCan_DataFieldSize_8;
    g_mcmcan1.canNodeConfig.rxConfig.rxFifo0Size = 15;

//    g_mcmcan1.canNodeConfig.filterConfig.messageIdLength = IfxCan_MessageIdLength_both;
//    g_mcmcan1.canNodeConfig.filterConfig.standardListSize = 1;
//    g_mcmcan1.canNodeConfig.filterConfig.extendedListSize = 0;
    g_mcmcan1.canNodeConfig.filterConfig.standardFilterForNonMatchingFrames = IfxCan_NonMatchingFrame_reject;
//    g_mcmcan1.canNodeConfig.filterConfig.extendedFilterForNonMatchingFrames = IfxCan_NonMatchingFrame_reject;
//    g_mcmcan1.canNodeConfig.filterConfig.rejectRemoteFramesWithStandardId = TRUE;
//    g_mcmcan1.canNodeConfig.filterConfig.rejectRemoteFramesWithExtendedId = TRUE;

    IfxCan_Can_initNode(&g_mcmcan1.canSrcNode, &g_mcmcan1.canNodeConfig);

    IfxCan_Can_initNode(&g_mcmcan1.canDstNode, &g_mcmcan1.canNodeConfig);

    IfxCan_Filter filter;

    filter.number = 0;
    filter.type = IfxCan_FilterType_range;
    filter.elementConfiguration = IfxCan_FilterElementConfiguration_storeInRxFifo0;
    filter.id1 = 11;
    filter.id2 = 20;
    //filter.rxBufferOffset = IfxCan_RxBufferId_0;
    IfxCan_Can_setStandardFilter(&g_mcmcan1.canDstNode, &filter);


    IfxCan_Can_initMessage(&g_mcmcan1.rxMsg);
    g_mcmcan1.rxMsg.readFromRxFifo0=TRUE;
    memset((void *)(&g_mcmcan1.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_DATA_PAYLOAD * sizeof(uint32));
    IfxCan_Can_initMessage(&g_mcmcan1.txMsg);
}

void initMcmcan2(void)
{
    IfxCan_Can_initModuleConfig(&g_mcmcan2.canConfig, &MODULE_CAN2);

    IfxCan_Can_initModule(&g_mcmcan2.canModule, &g_mcmcan2.canConfig);


    IfxCan_Can_initNodeConfig(&g_mcmcan2.canNodeConfig, &g_mcmcan2.canModule);


    g_mcmcan2.canNodeConfig.nodeId = IfxCan_NodeId_0;


    g_mcmcan2.canNodeConfig.frame.type = IfxCan_FrameType_transmitAndReceive;


    g_mcmcan2.canNodeConfig.baudRate.baudrate = 500000;
    g_mcmcan2.canNodeConfig.baudRate.prescaler = 0;
    g_mcmcan2.canNodeConfig.baudRate.samplePoint = 8000;
    g_mcmcan2.canNodeConfig.baudRate.syncJumpWidth = 2000;
    g_mcmcan2.canNodeConfig.baudRate.timeSegment1 = 3;
    g_mcmcan2.canNodeConfig.baudRate.timeSegment2 = 10;

    g_mcmcan2.canNodeConfig.pins = &Can2PortInf0;


    g_mcmcan2.canNodeConfig.interruptConfig.transmissionCompletedEnabled = TRUE;

    g_mcmcan2.canNodeConfig.interruptConfig.rxFifo0NewMessageEnabled = TRUE;


    g_mcmcan2.canNodeConfig.interruptConfig.traco.priority = ISR_PRIORITY_CAN2_TX;
    g_mcmcan2.canNodeConfig.interruptConfig.traco.interruptLine = IfxCan_InterruptLine_4;
    g_mcmcan2.canNodeConfig.interruptConfig.traco.typeOfService = IfxSrc_Tos_cpu3;



    g_mcmcan2.canNodeConfig.interruptConfig.rxf0n.priority = ISR_PRIORITY_CAN2_FIFO0_RX;
    g_mcmcan2.canNodeConfig.interruptConfig.rxf0n.interruptLine = IfxCan_InterruptLine_5;
    g_mcmcan2.canNodeConfig.interruptConfig.rxf0n.typeOfService = IfxSrc_Tos_cpu3;

    g_mcmcan2.canNodeConfig.rxConfig.rxMode = IfxCan_RxMode_fifo0;
    g_mcmcan2.canNodeConfig.rxConfig.rxFifo0DataFieldSize = IfxCan_DataFieldSize_8;
    g_mcmcan2.canNodeConfig.rxConfig.rxFifo0Size = 15;

//    g_mcmcan2.canNodeConfig.filterConfig.messageIdLength = IfxCan_MessageIdLength_both;
//    g_mcmcan2.canNodeConfig.filterConfig.standardListSize = 1;
//    g_mcmcan2.canNodeConfig.filterConfig.extendedListSize = 0;
    g_mcmcan2.canNodeConfig.filterConfig.standardFilterForNonMatchingFrames = IfxCan_NonMatchingFrame_reject;
//    g_mcmcan2.canNodeConfig.filterConfig.extendedFilterForNonMatchingFrames = IfxCan_NonMatchingFrame_reject;
//    g_mcmcan2.canNodeConfig.filterConfig.rejectRemoteFramesWithStandardId = TRUE;
//    g_mcmcan2.canNodeConfig.filterConfig.rejectRemoteFramesWithExtendedId = TRUE;

    IfxCan_Can_initNode(&g_mcmcan2.canSrcNode, &g_mcmcan2.canNodeConfig);

    IfxCan_Can_initNode(&g_mcmcan2.canDstNode, &g_mcmcan2.canNodeConfig);

    IfxCan_Filter filter;

    filter.number = 0;
    filter.type = IfxCan_FilterType_range;
    filter.elementConfiguration = IfxCan_FilterElementConfiguration_storeInRxFifo0;
    filter.id1 = 21;
    filter.id2 = 30;
    //filter.rxBufferOffset = IfxCan_RxBufferId_0;
    IfxCan_Can_setStandardFilter(&g_mcmcan2.canDstNode, &filter);


    IfxCan_Can_initMessage(&g_mcmcan2.rxMsg);
    g_mcmcan2.rxMsg.readFromRxFifo0=TRUE;
    memset((void *)(&g_mcmcan2.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_DATA_PAYLOAD * sizeof(uint32));
    IfxCan_Can_initMessage(&g_mcmcan2.txMsg);
}

/* Function to initialize both TX and RX messages with the default data values.
 * After initialization of the messages, the TX message is transmitted.
 */
void transmitCanMessage(void)
{
    /* Initialization of the RX message with the default configuration */
    IfxCan_Can_initMessage(&g_mcmcan.rxMsg);

    /* Invalidation of the RX message data content */
    memset((void *)(&g_mcmcan.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_DATA_PAYLOAD * sizeof(uint32));

    /* Initialization of the TX message with the default configuration */
//    IfxCan_Can_initMessage(&g_mcmcan.txMsg);

    /* Define the content of the data to be transmitted */
//    g_mcmcan.txData[0] = TX_DATA_LOW_WORD;
//    g_mcmcan.txData[1] = TX_DATA_HIGH_WORD;
//
//    /* Set the message ID that is used during the receive acceptance phase */
//    g_mcmcan.txMsg.messageId = 10;

    /* Send the CAN message with the previously defined TX message content */
    IfxCan_Can_sendMessage(&g_mcmcan.canSrcNode, &g_mcmcan.txMsg, &g_mcmcan.txData[0]);
//    while( IfxCan_Status_notSentBusy ==
//           IfxCan_Can_sendMessage(&g_mcmcan.canSrcNode, &g_mcmcan.txMsg, &g_mcmcan.txData[0]) )
//    {
//    }
}

void transmitCanMessage1(void)
{
    /* Initialization of the RX message with the default configuration */
    IfxCan_Can_initMessage(&g_mcmcan1.rxMsg);

    /* Invalidation of the RX message data content */
    memset((void *)(&g_mcmcan1.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_DATA_PAYLOAD * sizeof(uint32));

    /* Initialization of the TX message with the default configuration */
//    IfxCan_Can_initMessage(&g_mcmcan1.txMsg);

    /* Define the content of the data to be transmitted */
//    g_mcmcan1.txData[0] = TX_DATA_LOW_WORD;
//    g_mcmcan1.txData[1] = TX_DATA_HIGH_WORD;
//
//    /* Set the message ID that is used during the receive acceptance phase */
//    g_mcmcan1.txMsg.messageId = CAN_MESSAGE_ID;

    /* Send the CAN message with the previously defined TX message content */
    IfxCan_Can_sendMessage(&g_mcmcan1.canSrcNode, &g_mcmcan1.txMsg, &g_mcmcan1.txData[0]);
//    while( IfxCan_Status_notSentBusy ==
//           IfxCan_Can_sendMessage(&g_mcmcan1.canSrcNode, &g_mcmcan1.txMsg, &g_mcmcan1.txData[0]) )
//    {
//    }
}

void transmitCanMessage2(void)
{
    /* Initialization of the RX message with the default configuration */
    IfxCan_Can_initMessage(&g_mcmcan2.rxMsg);

    /* Invalidation of the RX message data content */
    memset((void *)(&g_mcmcan2.rxData[0]), INVALID_RX_DATA_VALUE, MAXIMUM_CAN_DATA_PAYLOAD * sizeof(uint32));

    /* Initialization of the TX message with the default configuration */
//    IfxCan_Can_initMessage(&g_mcmcan2.txMsg);

    /* Define the content of the data to be transmitted */
    //g_mcmcan2.txData[0] = TX_DATA_LOW_WORD;
    //g_mcmcan2.txData[1] = TX_DATA_HIGH_WORD;

    /* Set the message ID that is used during the receive acceptance phase */
    //g_mcmcan2.txMsg.messageId = CAN_MESSAGE_ID;

    //IfxCan_Can_sendMessage(&g_mcmcan2.canSrcNode, &g_mcmcan2.txMsg, &g_mcmcan2.txData[0]);

    /* Send the CAN message with the previously defined TX message content */
    while( IfxCan_Status_notSentBusy ==
           IfxCan_Can_sendMessage(&g_mcmcan2.canSrcNode, &g_mcmcan2.txMsg, &g_mcmcan2.txData[0]) )
    {
    }
}

/* Function to initialize the LEDs */
void initLeds(void)
{
    /* ======================================================================
     * Configuration of the pins connected to the LEDs:
     * ======================================================================
     *  - define the GPIO port
     *  - define the GPIO pin that is connected to the LED
     *  - define the general GPIO pin usage (no alternate function used)
     *  - define the pad driver strength
     * ======================================================================
     */
    g_led1.port      = &MODULE_P21;
    g_led1.pinIndex  = 4;
    g_led1.mode      = IfxPort_OutputIdx_general;
    g_led1.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    g_led2.port      = &MODULE_P21;
    g_led2.pinIndex  = 5;
    g_led2.mode      = IfxPort_OutputIdx_general;
    g_led2.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    g_led3.port      = &MODULE_P20;
    g_led3.pinIndex  = 9;
    g_led3.mode      = IfxPort_OutputIdx_general;
    g_led3.padDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1;

    /* Initialize the pins connected to LEDs to level "HIGH", which keep the LEDs turned off as default state */
    IfxPort_setPinHigh(g_led1.port, g_led1.pinIndex);
    IfxPort_setPinHigh(g_led2.port, g_led2.pinIndex);
    IfxPort_setPinHigh(g_led3.port, g_led3.pinIndex);

    /* Set the pin input/output mode for both pins connected to the LEDs */
    IfxPort_setPinModeOutput(g_led1.port, g_led1.pinIndex, IfxPort_OutputMode_pushPull, g_led1.mode);
    IfxPort_setPinModeOutput(g_led2.port, g_led2.pinIndex, IfxPort_OutputMode_pushPull, g_led2.mode);
    IfxPort_setPinModeOutput(g_led3.port, g_led3.pinIndex, IfxPort_OutputMode_pushPull, g_led3.mode);

    /* Set the pad driver mode for both pins connected to the LEDs */
    IfxPort_setPinPadDriver(g_led1.port, g_led1.pinIndex, g_led1.padDriver);
    IfxPort_setPinPadDriver(g_led2.port, g_led2.pinIndex, g_led2.padDriver);
    IfxPort_setPinPadDriver(g_led3.port, g_led3.pinIndex, g_led3.padDriver);
}

//
void intPortCan(void)
{
        IfxPort_setPinMode(&MODULE_P20,6, IfxPort_Mode_outputPushPullGeneral);
        IfxPort_setPinLow(&MODULE_P20,6);


}

