/**********************************************************************************************************************
 * \file SPI_CPU.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Qspi_L9658.h"
#include "IfxPort.h"
#include "FreeRTOS.h"
#include "task.h"
#include "CANTASK.h"
#include "MCMCAN.h"

#include "Bsp.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* QSPI modules */
#define QSPI1_MASTER                &MODULE_QSPI0   /* SPI Master module                                            */
//#define QSPI2_MASTER                &MODULE_QSPI2   /* SPI Master module                                            */
//#define QSPI3_SLAVE                 &MODULE_QSPI3   /* SPI Slave module                                             */
#define CS_PIN     &MODULE_P20,13

/* LED port pin */
#define LED_D110                    &MODULE_P10,6   /* LED D110 Port, Pin definition                                */

#define MASTER_CHANNEL_BAUDRATE     1000000         /* Master channel baud rate                                     */

/* Interrupt Service Routine priorities for Master and Slave SPI communication */
#define ISR_PRIORITY_MASTER_TX      50
#define ISR_PRIORITY_MASTER_RX      51
#define ISR_PRIORITY_MASTER_ER      52
//#define ISR_PRIORITY_SLAVE_TX       53
//#define ISR_PRIORITY_SLAVE_RX       54
//#define ISR_PRIORITY_SLAVE_ER       55

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
qspiComm g_qspi;



/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initQSPI1Master(void);
void initQSPI1MasterChannel(void);
//void initQSPI1MasterBuffers(void);
void initQSPI(void);
//void initLED(void);
void inittransferData(void);
void verifyData(void);
float32 PSI5_DataProcess(uint16 Data);

uint16 FL_Acc=0;
uint16 FR_Acc=0;
uint16 RL_Acc=0;
uint16 RR_Acc=0;

float32 f32_FL_Acc=0;
float32 f32_FR_Acc=0;
float32 f32_RL_Acc=0;
float32 f32_RR_Acc=0;

uint16 ii=0;
uint16 p2013 = 2;
uint16 p20131 = 2;
uint16 p20132 = 2;

uint16 recdata1=0, recdata2=0, recdata3=0, recdata4=0;
uint16 recdata5=0, recdata6=0, recdata7=0, recdata8=0;

/*********************************************************************************************************************/
/*----------------------------------------------Function Implementations---------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(masterTxISR, 0, ISR_PRIORITY_MASTER_TX);                  /* SPI Master ISR for transmit data         */
IFX_INTERRUPT(masterRxISR, 0, ISR_PRIORITY_MASTER_RX);                  /* SPI Master ISR for receive data          */
IFX_INTERRUPT(masterErISR, 0, ISR_PRIORITY_MASTER_ER);                  /* SPI Master ISR for error                 */


void masterTxISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrTransmit(&g_qspi.spiMaster);

//    IfxPort_setPinState(g_led1.port, g_led1.pinIndex,  IfxPort_State_toggled);
}

void masterRxISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrReceive(&g_qspi.spiMaster);

//    IfxPort_setPinState(g_led2.port, g_led2.pinIndex,  IfxPort_State_toggled);

}

void masterErISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrError(&g_qspi.spiMaster);
}


/* QSPI Master initialization
 * This function initializes the QSPI2 module in Master mode.
 */


void initQSPI1Master(void)
{
    IfxQspi_SpiMaster_Config spiMasterConfig;                           /* Define a Master configuration            */

    IfxQspi_SpiMaster_initModuleConfig(&spiMasterConfig, QSPI1_MASTER); /* Initialize it with default values        */

    spiMasterConfig.base.mode = SpiIf_Mode_master;                      /* Configure the mode                       */

    /* Select the port pins for communication */
    const IfxQspi_SpiMaster_Pins qspi1MasterPins = {
        &IfxQspi0_SCLK_P20_11_OUT, IfxPort_OutputMode_pushPull,          /* SCLK Pin                       (CLK)     */
        &IfxQspi0_MTSR_P20_14_OUT, IfxPort_OutputMode_pushPull,          /* MasterTransmitSlaveReceive pin (MOSI)    */
        &IfxQspi0_MRSTA_P20_12_IN, IfxPort_InputMode_pullDown,           /* MasterReceiveSlaveTransmit pin (MISO)    */
        IfxPort_PadDriver_cmosAutomotiveSpeed1                          /* Pad driver mode                          */
    };
    spiMasterConfig.pins = &qspi1MasterPins;                            /* Assign the Master's port pins            */

    /* Set the ISR priorities and the service provider */
    spiMasterConfig.base.txPriority = ISR_PRIORITY_MASTER_TX;
    spiMasterConfig.base.rxPriority = ISR_PRIORITY_MASTER_RX;
    spiMasterConfig.base.erPriority = ISR_PRIORITY_MASTER_ER;
    spiMasterConfig.base.isrProvider = IfxSrc_Tos_cpu0;

    /* Initialize the QSPI Master module */
    IfxQspi_SpiMaster_initModule(&g_qspi.spiMaster, &spiMasterConfig);
}

/* QSPI Master channel initialization
 * This function initializes the QSPI1 Master channel.
 */
void initQSPI1MasterChannel(void)
{
    IfxQspi_SpiMaster_ChannelConfig spiMasterChannelConfig;             /* Define a Master Channel configuration    */

    /* Initialize the configuration with default values */
    IfxQspi_SpiMaster_initChannelConfig(&spiMasterChannelConfig, &g_qspi.spiMaster);

    spiMasterChannelConfig.base.baudrate = 1000000;     /* Set SCLK frequency to 1 MHz              */
    spiMasterChannelConfig.base.mode.clockPolarity   = SpiIf_ClockPolarity_idleLow;
//    spiMasterChannelConfig.base.mode.shiftClock    = SpiIf_ShiftClock_shiftTransmitDataOnLeadingEdge;
//    spiMasterChannelConfig.base.mode.clockPolarity   = SpiIf_ClockPolarity_idleHigh;
    spiMasterChannelConfig.base.mode.shiftClock    = SpiIf_ShiftClock_shiftTransmitDataOnTrailingEdge;

    spiMasterChannelConfig.base.mode.dataHeading = SpiIf_DataHeading_msbFirst;
    spiMasterChannelConfig.base.mode.dataWidth   = 16;
    spiMasterChannelConfig.base.mode.csActiveLevel = Ifx_ActiveState_high;
    spiMasterChannelConfig.base.mode.autoCS = 1;
//    spiMasterChannelConfig.base.mode.autoCS = 0;
//    spiMasterChannelConfig.base.mode.csLeadDelay = 1;
    spiMasterChannelConfig.base.mode.csTrailDelay = 0;
    spiMasterChannelConfig.base.mode.csInactiveDelay = 0;

    /* Select the port pin for the Chip Select signal */
    const IfxQspi_SpiMaster_Output qspi1SlaveSelect = {                 /* QSPI1 Master selects the QSPI1 Slave     */
        &IfxQspi0_SLSO2_P20_13_OUT, IfxPort_OutputMode_pushPull,         /* Slave Select port pin (CS)               */
        IfxPort_PadDriver_cmosAutomotiveSpeed1                          /* Pad driver mode                          */
    };
    spiMasterChannelConfig.sls.output = qspi1SlaveSelect;

    /* Initialize the QSPI Master channel */
    IfxQspi_SpiMaster_initChannel(&g_qspi.spiMasterChannel, &spiMasterChannelConfig);

}


void PSI5_ACC_TASK()
{
//    initQSPI();
//    for(;;)
//    {
//        transferData();
//        printf("FL_Acc = %d , FR_Acc = %d , RL_Acc = %d , RR_Acc = %d \r\n",
//                FL_Acc, FR_Acc, RL_Acc, RR_Acc);
//        vTaskDelay(pdMS_TO_TICKS(5));
//
//    }
}


/* This function initialize the QSPI modules */
void initQSPI(void)
{
    /* Firstly initialize the Master */
    initQSPI1Master();
    initQSPI1MasterChannel();
    inittransferData();

}

/* This function to initialize the QSPI modules and the LED */
void initPeripherals(void)
{
//    initLED();
    initQSPI();
//    IfxPort_setPinMode(CS_PIN, IfxPort_Mode_outputPushPullGeneral);
//    IfxPort_setPinState(CS_PIN, IfxPort_State_low);
}

/* This function starts the data transfer */
void inittransferData(void)
{
//    Ifx_TickTime ticksFor10ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 10);

    g_qspi.spiBuffers.spiMasterTxBuffer[0]=0x8F00;
    g_qspi.spiBuffers.spiMasterTxBuffer[1]=0x8F00;
    g_qspi.spiBuffers.spiMasterTxBuffer[2]=0xC3A2;
    g_qspi.spiBuffers.spiMasterTxBuffer[3]=0xC3A2;
    g_qspi.spiBuffers.spiMasterTxBuffer[4]=0xC3A2;

    for (uint8 i = 0; i < 20; i++)
    {
        g_qspi.spiBuffers.spiMasterRxBuffer[i] = 0;                     /* Clear RX Buffer                          */
    }

//    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy)
//    {   /* Wait until the previous communication has finished, if any */
//    }
    /* Send a data stream through the SPI Master */
//    IfxPort_setPinState(CS_PIN,  IfxPort_State_high);

//    IfxQspi_SpiMaster_exchange(&g_qspi.spiMasterChannel, &g_qspi.spiBuffers.spiMasterTxBuffer[0], &g_qspi.spiBuffers.spiMasterRxBuffer[0], 1);
//    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy){};

//    IfxPort_setPinState(CS_PIN,  IfxPort_State_low);


//    IfxPort_setPinState(CS_PIN,  IfxPort_State_high);

    IfxQspi_SpiMaster_exchange(&g_qspi.spiMasterChannel, &g_qspi.spiBuffers.spiMasterTxBuffer[1], &g_qspi.spiBuffers.spiMasterRxBuffer[1], 4);

    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy){};
//        waitTime(ticksFor10ms/1000);

//    IfxPort_setPinState(CS_PIN,  IfxPort_State_low);

//    p2013=IfxPort_getPinState(&MODULE_P20,13);
//
//    g_qspi.spiBuffers.spiMasterTxBuffer[0]=0x8F00;
//    g_qspi.spiBuffers.spiMasterTxBuffer[1]=0xC3A2;
//    g_qspi.spiBuffers.spiMasterTxBuffer[2]=0xC3A2;
//    g_qspi.spiBuffers.spiMasterTxBuffer[3]=0xC3A2;
//    g_qspi.spiBuffers.spiMasterTxBuffer[4]=0xC3A2;
    g_qspi.spiBuffers.spiMasterTxBuffer[5]=0xC3A2;
    g_qspi.spiBuffers.spiMasterTxBuffer[6]=0xC3A2;
    g_qspi.spiBuffers.spiMasterTxBuffer[7]=0xC3A2;
    g_qspi.spiBuffers.spiMasterTxBuffer[8]=0xC3A2;

//    for (uint8 i = 0; i < 5; i++)
//    {
//        g_qspi.spiBuffers.spiMasterRxBuffer[i] = 0;                     /* Clear RX Buffer                          */
//    }
//
//    waitTime(ticksFor10ms/10000);
//    IfxPort_setPinState(CS_PIN,  IfxPort_State_high);

    IfxQspi_SpiMaster_exchange(&g_qspi.spiMasterChannel, &g_qspi.spiBuffers.spiMasterTxBuffer[5], &g_qspi.spiBuffers.spiMasterRxBuffer[5], 4);
//    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy){};

//    IfxQspi_SpiMaster_exchange(&g_qspi.spiMasterChannel, &g_qspi.spiBuffers.spiMasterTxBuffer[1], &g_qspi.spiBuffers.spiMasterRxBuffer[1], 4);


    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy){};
//    waitTime(ticksFor10ms/10000);
//    IfxPort_setPinState(CS_PIN,  IfxPort_State_low);


//    waitTime(ticksFor10ms);
    recdata1 = g_qspi.spiBuffers.spiMasterRxBuffer[1];
    recdata2 = g_qspi.spiBuffers.spiMasterRxBuffer[2];
    recdata3 = g_qspi.spiBuffers.spiMasterRxBuffer[3];
    recdata4 = g_qspi.spiBuffers.spiMasterRxBuffer[4];
    recdata5 = g_qspi.spiBuffers.spiMasterRxBuffer[5];
    recdata6 = g_qspi.spiBuffers.spiMasterRxBuffer[6];
    recdata7 = g_qspi.spiBuffers.spiMasterRxBuffer[7];
    recdata8 = g_qspi.spiBuffers.spiMasterRxBuffer[8];


}

void transferData(void)
{

//    for (uint8 i = 0; i < 20; i++)
//    {
//        g_qspi.spiBuffers.spiMasterRxBuffer[i] = 0;                     /* Clear RX Buffer                          */
//    }

//    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy){};
//    g_qspi.spiBuffers.spiMasterTxBuffer[9]=0x5782;
    g_qspi.spiBuffers.spiMasterTxBuffer[9]=0x5FA2;
    g_qspi.spiBuffers.spiMasterTxBuffer[10]=0x5FA2;
    g_qspi.spiBuffers.spiMasterTxBuffer[11]=0x5FA2;
    g_qspi.spiBuffers.spiMasterTxBuffer[12]=0x5FA2;

//    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy)
//    {   /* Wait until the previous communication has finished, if any */
//    }

//    IfxPort_setPinState(CS_PIN,  IfxPort_State_high);

    /* Send a data stream through the SPI Master */
    IfxQspi_SpiMaster_exchange(&g_qspi.spiMasterChannel, &g_qspi.spiBuffers.spiMasterTxBuffer[9], &g_qspi.spiBuffers.spiMasterRxBuffer[9], 4);

    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy){};

//    IfxPort_setPinState(CS_PIN,  IfxPort_State_low);


    verifyData();
}

/* This function checks if the received data is correct */
void verifyData(void)
{
    FL_Acc=g_qspi.spiBuffers.spiMasterRxBuffer[9];
    FR_Acc=g_qspi.spiBuffers.spiMasterRxBuffer[10];
    RL_Acc=g_qspi.spiBuffers.spiMasterRxBuffer[11];
    RR_Acc=g_qspi.spiBuffers.spiMasterRxBuffer[12];
    f32_FL_Acc = PSI5_DataProcess(FL_Acc);
    f32_FR_Acc = PSI5_DataProcess(FR_Acc);
    f32_RL_Acc = PSI5_DataProcess(RL_Acc);
    f32_RR_Acc = PSI5_DataProcess(RR_Acc);
}

float32 PSI5_DataProcess(uint16 Data)       //PSI5加速度传感器信号值处理函数
{
  uint16 Acc_Data,Acc_RevData,Acc_temp,Bit_temp;
  float32 Acc;
  uint8 k;

  Acc_RevData=Data&0x3FF;               //取出D0~D9的10位有效信号值，此时取出的值为倒序

  Acc_Data=0;                           //Acc_Data用于存储正序的信号值
  for(k=0;k<10;k++)                     //对10位的PSI5信号值进行位倒序
  {
    Bit_temp=Acc_RevData&0x001;
    Acc_RevData=Acc_RevData>>1;
    Acc_Data=Acc_Data+Bit_temp;
    if(k!=9)
      Acc_Data=Acc_Data<<1;
  }

  if(Acc_Data>=0x000&&Acc_Data<=0x1E0)
    Acc=(Acc_Data/300.00)*9.81;              //在加速度信号值>0时将接收到的值转化成物理值，加速度方向和g相同（向下为正）
  else if(Acc_Data>=0x220&&Acc_Data<=0x3FF)
  {
    Acc_temp=(~(Acc_Data)&0x01FF)+1;         //在加速度信号值<0时将接收到的补码转化成原码
    Acc=0.00-(Acc_temp/300.00*9.81);         //转化成物理值，加速度方向和g相反（向上为负）
  }
  else                                       //若PSI5信号值为非数字值，则视加速度为0
    Acc=0;

//  if(Acc<5&&Acc>-5)
//  Acc=0;

  return Acc;
}
