/**********************************************************************************************************************
 * \file SPI_CPU.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Qspi_L9658.h"
#include "IfxPort.h"
#include "FreeRTOS.h"
#include "task.h"
#include "CANTASK.h"
#include "MCMCAN.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* QSPI modules */
#define QSPI1_MASTER                &MODULE_QSPI1   /* SPI Master module                                            */
#define QSPI2_MASTER                &MODULE_QSPI2   /* SPI Master module                                            */
#define QSPI3_SLAVE                 &MODULE_QSPI3   /* SPI Slave module                                             */

/* LED port pin */
#define LED_D110                    &MODULE_P13,3   /* LED D110 Port, Pin definition                                */

#define MASTER_CHANNEL_BAUDRATE     1000000         /* Master channel baud rate                                     */

/* Interrupt Service Routine priorities for Master and Slave SPI communication */
#define ISR_PRIORITY_MASTER_TX      50
#define ISR_PRIORITY_MASTER_RX      51
#define ISR_PRIORITY_MASTER_ER      52
#define ISR_PRIORITY_SLAVE_TX       53
#define ISR_PRIORITY_SLAVE_RX       54
#define ISR_PRIORITY_SLAVE_ER       55

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
qspiComm g_qspi;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void initQSPI1Master(void);
void initQSPI1MasterChannel(void);
void initQSPI1MasterBuffers(void);
void initQSPI(void);
void initLED(void);
void inittransferData(void);
void verifyData(void);
float PSI5_DataProvess(uint16 Data);

uint16 FL_Acc=0;
uint16 FR_Acc=0;
uint16 RL_Acc=0;
uint16 RR_Acc=0;


/*********************************************************************************************************************/
/*----------------------------------------------Function Implementations---------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(masterTxISR, 0, ISR_PRIORITY_MASTER_TX);                  /* SPI Master ISR for transmit data         */
IFX_INTERRUPT(masterRxISR, 0, ISR_PRIORITY_MASTER_RX);                  /* SPI Master ISR for receive data          */
IFX_INTERRUPT(masterErISR, 0, ISR_PRIORITY_MASTER_ER);                  /* SPI Master ISR for error                 */


void masterTxISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrTransmit(&g_qspi.spiMaster);

    IfxPort_setPinState(g_led1.port, g_led1.pinIndex,  IfxPort_State_toggled);
}

void masterRxISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrReceive(&g_qspi.spiMaster);

    IfxPort_setPinState(g_led2.port, g_led2.pinIndex,  IfxPort_State_toggled);

}

void masterErISR()
{
    IfxCpu_enableInterrupts();
    IfxQspi_SpiMaster_isrError(&g_qspi.spiMaster);
}


/* QSPI Master initialization
 * This function initializes the QSPI2 module in Master mode.
 */


void initQSPI1Master(void)
{
    IfxQspi_SpiMaster_Config spiMasterConfig;                           /* Define a Master configuration            */
    IfxQspi_SpiMaster_initModuleConfig(&spiMasterConfig, QSPI1_MASTER); /* Initialize it with default values        */
    spiMasterConfig.base.mode = SpiIf_Mode_master;                      /* Configure the mode                       */
    const IfxQspi_SpiMaster_Pins qspi1MasterPins = {
        &IfxQspi1_SCLK_P10_2_OUT, IfxPort_OutputMode_pushPull,          /* SCLK Pin                       (CLK)     */
        &IfxQspi1_MTSRA_P10_3_IN, IfxPort_OutputMode_pushPull,          /* MasterTransmitSlaveReceive pin (MOSI)    */
        &IfxQspi1_MRSTA_P10_1_IN, IfxPort_InputMode_pullDown,           /* MasterReceiveSlaveTransmit pin (MISO)    */
        IfxPort_PadDriver_cmosAutomotiveSpeed3                          /* Pad driver mode                          */
    };
    spiMasterConfig.pins = &qspi1MasterPins;                            /* Assign the Master's port pins            */

    /* Set the ISR priorities and the service provider */
    spiMasterConfig.base.txPriority = ISR_PRIORITY_MASTER_TX;
    spiMasterConfig.base.rxPriority = ISR_PRIORITY_MASTER_RX;
    spiMasterConfig.base.erPriority = ISR_PRIORITY_MASTER_ER;
    spiMasterConfig.base.isrProvider = IfxSrc_Tos_cpu0;

    /* Initialize the QSPI Master module */
    IfxQspi_SpiMaster_initModule(&g_qspi.spiMaster, &spiMasterConfig);
}


void initQSPI1MasterChannel(void)
{
    IfxQspi_SpiMaster_ChannelConfig spiMasterChannelConfig;             /* Define a Master Channel configuration    */

    /* Initialize the configuration with default values */
    IfxQspi_SpiMaster_initChannelConfig(&spiMasterChannelConfig, &g_qspi.spiMaster);

    spiMasterChannelConfig.base.baudrate = MASTER_CHANNEL_BAUDRATE;     /* Set SCLK frequency to 1 MHz              */

    /* Select the port pin for the Chip Select signal */
    const IfxQspi_SpiMaster_Output qspi1SlaveSelect = {                 /* QSPI2 Master selects the QSPI3 Slave     */
        &IfxQspi1_SLSO9_P10_5_OUT, IfxPort_OutputMode_pushPull,         /* Slave Select port pin (CS)               */
        IfxPort_PadDriver_cmosAutomotiveSpeed1                          /* Pad driver mode                          */
    };
    spiMasterChannelConfig.sls.output = qspi1SlaveSelect;

    /* Initialize the QSPI Master channel */
    IfxQspi_SpiMaster_initChannel(&g_qspi.spiMasterChannel, &spiMasterChannelConfig);
}

void initQSPI1MasterBuffers(void)
{
    g_qspi.spiBuffers.spiMasterTxBuffer[0]=0x8F00;
    g_qspi.spiBuffers.spiMasterTxBuffer[1]=0xC3A2;
    g_qspi.spiBuffers.spiMasterTxBuffer[2]=0xC3A2;
    g_qspi.spiBuffers.spiMasterTxBuffer[3]=0xC3A2;
    g_qspi.spiBuffers.spiMasterTxBuffer[4]=0xC3A2;

//    for (uint8 i = 0; i < 5; i++)
//    {
//        g_qspi.spiBuffers.spiMasterRxBuffer[i] = 0;                     /* Clear RX Buffer                          */
//    }
}

void readQSPI1MasterBuffers(void)
{
    g_qspi.spiBuffers.spiMasterTxBuffer[0]=0x5FA2;
    g_qspi.spiBuffers.spiMasterTxBuffer[1]=0x5FA2;
    g_qspi.spiBuffers.spiMasterTxBuffer[2]=0x5FA2;
    g_qspi.spiBuffers.spiMasterTxBuffer[3]=0x5FA2;
//    for (uint8 i = 0; i < 4; i++)
//    {
//        g_qspi.spiBuffers.spiMasterRxBuffer[i] = 0;                     /* Clear RX Buffer                          */
//    }

}

void PSI5_ACC_TASK()
{
    initQSPI();
    for(;;)
    {
        transferData();
        printf("FL_Acc = %d , FR_Acc = %d , RL_Acc = %d , RR_Acc = %d \r\n",
                FL_Acc, FR_Acc, RL_Acc, RR_Acc);
        vTaskDelay(pdMS_TO_TICKS(5));

    }
}


/* This function initialize the QSPI modules */
void initQSPI(void)
{
    /* Firstly initialize the Master */
    initQSPI1Master();
    initQSPI1MasterChannel();
    inittransferData();

}

/* This function to initialize the QSPI modules and the LED */
void initPeripherals(void)
{
    initLED();
    initQSPI();
}

/* This function starts the data transfer */
void inittransferData(void)
{
    initQSPI1MasterBuffers();

    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy)
    {   /* Wait until the previous communication has finished, if any */
    }
    /* Send a data stream through the SPI Master */
    IfxQspi_SpiMaster_exchange(&g_qspi.spiMasterChannel, &g_qspi.spiBuffers.spiMasterTxBuffer[0], &g_qspi.spiBuffers.spiMasterRxBuffer[0], 5);

}

void transferData(void)
{
    readQSPI1MasterBuffers();

    while(IfxQspi_SpiMaster_getStatus(&g_qspi.spiMasterChannel) == SpiIf_Status_busy)
    {   /* Wait until the previous communication has finished, if any */
    }
    /* Send a data stream through the SPI Master */
    IfxQspi_SpiMaster_exchange(&g_qspi.spiMasterChannel, &g_qspi.spiBuffers.spiMasterTxBuffer[0], &g_qspi.spiBuffers.spiMasterRxBuffer[0], 4);

    verifyData();
}

/* This function checks if the received data is correct */
void verifyData(void)
{
    FL_Acc=g_qspi.spiBuffers.spiMasterRxBuffer[0];
    FR_Acc=g_qspi.spiBuffers.spiMasterRxBuffer[1];
    RL_Acc=g_qspi.spiBuffers.spiMasterRxBuffer[2];
    RR_Acc=g_qspi.spiBuffers.spiMasterRxBuffer[3];
}

float PSI5_DataProcess(uint16 Data)       //PSI5加速度传感器信号值处理函数
{
  uint16 Acc_Data,Acc_RevData,Acc_temp,Bit_temp;
  float Acc;
  char k;

  Acc_RevData=Data&0x3FF;               //取出D0~D9的10位有效信号值，此时取出的值为倒序

  Acc_Data=0;                           //Acc_Data用于存储正序的信号值
  for(k=0;k<10;k++)                     //对10位的PSI5信号值进行位倒序
  {
    Bit_temp=Acc_RevData&0x001;
    Acc_RevData=Acc_RevData>>1;
    Acc_Data=Acc_Data+Bit_temp;
    if(k!=9)
      Acc_Data=Acc_Data<<1;
  }

  if(Acc_Data>=0x000&&Acc_Data<=0x1E0)
    Acc=(Acc_Data/300.00)*9.81*10;              //在加速度信号值>0时将接收到的值转化成物理值，加速度方向和g相同（向下为正）
  else if(Acc_Data>=0x220&&Acc_Data<=0x3FF)
  {
    Acc_temp=(~(Acc_Data)&0x01FF)+1;         //在加速度信号值<0时将接收到的补码转化成原码
    Acc=0.00-(Acc_temp/300.00*9.81*10);         //转化成物理值，加速度方向和g相反（向上为负）
  }
  else                                       //若PSI5信号值为非数字值，则视加速度为0
    Acc=0;

  if(Acc<5&&Acc>-5)
  Acc=0;

  return Acc;
}
