/**********************************************************************************************************************
 * \file Drive_Output.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Drive_Output.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
static float32 ff; //get clk frequency
IfxGtm_Tom_Pwm_Config g_tomConfig;                                  /* Timer configuration structure                */
IfxGtm_Tom_Pwm_Driver g_tomDriver;                                  /* Timer Driver structure  */
float32 myfrequency = 2500;   //output pwm frequency hz
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/


void GTM_Tom_init(void)
{
    IfxGtm_enable(&MODULE_GTM);                                     /* Enable GTM                                   */
    IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_FXCLK);   /* Enable the FXU clock                         */

    ff = IfxGtm_Cmu_getFxClkFrequency(&MODULE_GTM,IfxGtm_Cmu_Fxclk_0, 1);  //global clock0 100MHz

    //PWM0
    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig, &MODULE_GTM);

    g_tomConfig.tom = IfxGtm_TOM0_0_TOUT0_P02_0_OUT.tom;                                      /* Select the TOM depending on the LED          */
    g_tomConfig.tomChannel = IfxGtm_TOM0_0_TOUT0_P02_0_OUT.channel;                           /* Select the channel depending on the LED      */
    g_tomConfig.period = ff / myfrequency;                                /* Set the timer period                         */
    g_tomConfig.pin.outputPin = &IfxGtm_TOM0_0_TOUT0_P02_0_OUT;                               /* Set the LED port pin as output               */
    g_tomConfig.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */
    g_tomConfig.clock = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk0;  // divide 1

    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_tomDriver, TRUE);                      /* Start the PWM */

    //PWM1
    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig, &MODULE_GTM);

    g_tomConfig.tom = IfxGtm_TOM0_1_TOUT1_P02_1_OUT.tom;                                      /* Select the TOM depending on the LED          */
    g_tomConfig.tomChannel = IfxGtm_TOM0_1_TOUT1_P02_1_OUT.channel;                           /* Select the channel depending on the LED      */
    g_tomConfig.period = ff / myfrequency;                                /* Set the timer period                         */
    g_tomConfig.pin.outputPin = &IfxGtm_TOM0_1_TOUT1_P02_1_OUT;                               /* Set the LED port pin as output               */
    g_tomConfig.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */
    g_tomConfig.clock = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk0;  // divide 16

    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_tomDriver, TRUE);                       /* Start the PWM */

    //PMW2
    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig, &MODULE_GTM);

    g_tomConfig.tom = IfxGtm_TOM0_2_TOUT2_P02_2_OUT.tom;                                      /* Select the TOM depending on the LED          */
    g_tomConfig.tomChannel = IfxGtm_TOM0_2_TOUT2_P02_2_OUT.channel;                           /* Select the channel depending on the LED      */
    g_tomConfig.period = ff / myfrequency;                                /* Set the timer period                         */
    g_tomConfig.pin.outputPin = &IfxGtm_TOM0_2_TOUT2_P02_2_OUT;                               /* Set the LED port pin as output               */
    g_tomConfig.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */
    g_tomConfig.clock = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk0;  // divide 16

    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_tomDriver, TRUE);                       /* Start the PWM */

    //PMW3
    /* Initialize the configuration structure with default parameters */
    IfxGtm_Tom_Pwm_initConfig(&g_tomConfig, &MODULE_GTM);

    g_tomConfig.tom = IfxGtm_TOM0_3_TOUT3_P02_3_OUT.tom;                                      /* Select the TOM depending on the LED          */
    g_tomConfig.tomChannel = IfxGtm_TOM0_3_TOUT3_P02_3_OUT.channel;                           /* Select the channel depending on the LED      */
    g_tomConfig.period = ff / myfrequency;                                /* Set the timer period                         */
    g_tomConfig.pin.outputPin = &IfxGtm_TOM0_3_TOUT3_P02_3_OUT;                               /* Set the LED port pin as output               */
    g_tomConfig.synchronousUpdateEnabled = TRUE;                    /* Enable synchronous update                    */
    g_tomConfig.clock = IfxGtm_Tom_Ch_ClkSrc_cmuFxclk0;  // divide 16

    IfxGtm_Tom_Pwm_init(&g_tomDriver, &g_tomConfig);                /* Initialize the GTM TOM                       */
    IfxGtm_Tom_Pwm_start(&g_tomDriver, TRUE);                       /* Start the PWM */

    PWM_Control(0, 400);
}

void PWM_Control(uint8 PortNum, uint16 PwmDuty)
{
    IfxGtm_Tom_Pwm_Config *config = &g_tomConfig;
    uint16 Ctl_Duty;
    PwmDuty = PwmDuty > 1000 ? 1000 : PwmDuty;
    Ctl_Duty = ((config->period) * PwmDuty) / 1000;
    Ifx_GTM_TOM *tomSFR = &config->gtm->TOM[config->tom];
    IfxGtm_Tom_Ch_setCompareOneShadow(tomSFR, PortNum, Ctl_Duty);
    //IfxGtm_Tom_Ch_setCompareOneShadow(&MODULE_GTM.TOM[0], PortNum, Ctl_Duty);
}

