/**********************************************************************************************************************
 * \file Schedule.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Schedule.h"
#include "IfxPort.h"
#include "CANTask.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_STM        40                              /* Priority for interrupt ISR                       */
#define TIMER_INT_TIME          5                           /* Time between interrupts in ms                    */

#define LED1                     &MODULE_P20,8                   /* LED toggled in Interrupt Service Routine (ISR)   */
#define LED2                     &MODULE_P20,9
#define LED3                     &MODULE_P21,4
#define STM3                     &MODULE_STM3

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
IfxStm_CompareConfig g_STMConf;                                 /* STM configuration structure                      */
uint32 g_ticksFor5ms;                                   /* Variable to store the number of ticks to wait    */

uint64 Schedule_call=0;
uint8 task1;
uint8 task2;
uint8 task3;
//uint8 count=0;

uint8 Schedule_time(uint8 time);
uint8 Schedule_call_update(void);
void Schedule(void);

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void isrSTM(void);
void initLED(void);

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
/* Macro to define Interrupt Service Routine.
 * This macro makes following definitions:
 * 1) Define linker section as .intvec_tc<vector number>_<interrupt priority>.
 * 2) define compiler specific attribute for the interrupt functions.
 * 3) define the Interrupt service routine as ISR function.
 *
 * IFX_INTERRUPT(isr, vectabNum, priority)
 *  - isr: Name of the ISR function.
 *  - vectabNum: Vector table number.
 *  - priority: Interrupt priority. Refer Usage of Interrupt Macro for more details.
 */
IFX_INTERRUPT(isrSTM, 3, ISR_PRIORITY_STM);

void isrSTM(void)
{
    /* Update the compare register value that will trigger the next interrupt and toggle the LED */
    IfxStm_increaseCompare(STM3, g_STMConf.comparator, g_ticksFor5ms);
//    IfxPort_setPinState(LED, IfxPort_State_toggled);
    Schedule_call++;
}

/* Function to initialize the STM */
void initSTM(void)
{
    /* Initialize time constant */
    g_ticksFor5ms = IfxStm_getTicksFromMilliseconds(STM3, TIMER_INT_TIME);

    IfxStm_initCompareConfig(&g_STMConf);           /* Initialize the configuration structure with default values   */

    g_STMConf.triggerPriority = ISR_PRIORITY_STM;   /* Set the priority of the interrupt                            */
    g_STMConf.typeOfService = IfxSrc_Tos_cpu3;      /* Set the service provider for the interrupts                  */
    g_STMConf.ticks = g_ticksFor5ms;              /* Set the number of ticks after which the timer triggers an
                                                     * interrupt for the first time                                 */
    IfxStm_initCompare(STM3, &g_STMConf);            /* Initialize the STM with the user configuration               */
    IfxStm_enableOcdsSuspend(STM3);

    initLED();
}

/* Function to initialize the LED */
void initLED(void)
{
    IfxPort_setPinMode(LED1, IfxPort_Mode_outputPushPullGeneral);    /* Initialize LED port pin                      */
    IfxPort_setPinState(LED1, IfxPort_State_high);                   /* Turn off LED (LED is low-level active)       */
    IfxPort_setPinMode(LED2, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinState(LED2, IfxPort_State_high);
    IfxPort_setPinMode(LED3, IfxPort_Mode_outputPushPullGeneral);
    IfxPort_setPinState(LED3, IfxPort_State_high);
}

uint8 Schedule_time(uint8 time)
{
    if(Schedule_call>0&&Schedule_call%time==0){
        return 1;
    }else{
        return 0;
    }
}

uint8 Schedule_call_update(void)
{
    static uint64 call = 0;
    if (call == Schedule_call){
        return 0;
    }else{
        call = Schedule_call;
        return 1;
    }
}

void Schedule(void)
{
    task1 = Schedule_time(1);
    task2 = Schedule_time(2);
    task3 = Schedule_time(3);
}

void run_schedule(void)
{
    if( Schedule_call_update()){
        Schedule();
        if(task1){
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);
            CAN2Data_Send(2);


//            IfxPort_setPinState(LED1, IfxPort_State_toggled);
        }
        if(task2){
            CAN2Data_Send(1);
//            IfxPort_setPinState(LED2, IfxPort_State_toggled);
        }
        if(task3){
//            IfxPort_setPinState(LED3, IfxPort_State_toggled);
        }
    }
}
